# Generated by Django 6.0 on 2026-03-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('taskcompleted', models.BooleanField()),
            ],
        ),
    ]
